#!/usr/bin/env node

'use strict'


var map = require('map-stream');
var vfs = require('vinyl-fs');

var log = function(file, cb) {
  console.log(file.path);
  cb(null, file);
};

vfs.src(['./components/**/*.md'])
  .pipe(map(log))
  .pipe(vfs.dest('./build/docs'));




/*
# Documentator

This tool do something!!!!!!!

## Resources:

https://github.com/emiloberg/markdown-styleguide-generator
https://www.npmjs.com/package/line-read

## Notes [pt-br]

- gerar um json chamado tools.json na pasta build
- nesse arquivo irao conter objetos chamados tools
- contendo comentarios extraidos do código
- cada tool vai ter uma seçao na pagina
- o conteudo vai ser interpretado como frontmatter
- o site vai ser react


a documentacao dos scripts vao ter um site exclusivo.

a documentacao dessa tool vai ser só a do frontmatter

tentar fazer subprocessos, tipo: frontmatter "diretorio"



*/

/**
 * Read configuration
 */
